---
name: module3_task5

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"  # Download code from the repository
        uses: actions/checkout@v3

      - name: "Run bash script"
        run: cd module3_task5 && ./setup.sh

      - name: "Run make build"  # Execute the command make build
        run: cd module3_task5 && make build

      - name: "Testing"
        run: |
          cd module3_task5 && make validate
          make integration-tests
          make unit-tests
          make package
          make clean

      - name: Release
        env:
          TOKEN: ${{ secrets.TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.1
          files: |
            module3_task5/awesome-website.zip
            module3_task5/DEPLOY.md

      - name: "archive build"
        uses: actions/upload-artifact@v3
        with:
          name: "upload package"
          path: module3_task5/awesome-website.zip

      - name: deploy-preview
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './module3_task5/dist'
          github-token: ${{ secrets.TOKEN }}
          deploy-message: 'Published on'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: deploy-production
        if: github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './module3_task5/dist'
          github-token: ${{ secrets.TOKEN }}
          deploy-message: 'Published on'
          production-branch: 'main'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
